# Generated by Django 3.0.3 on 2020-02-27 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.TextField()),
                ('users', models.ManyToManyField(related_name='organization', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
