# Generated by Django 3.0.3 on 2020-03-04 07:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(verbose_name='Company address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='organization', to=settings.AUTH_USER_MODEL),
        ),
    ]
