# Generated by Django 3.0.3 on 2020-03-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='report_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sampling_point',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
